name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Print branch name
        run: echo "${{ github.ref }}"
      - name: Print changed files
        run: git diff --name-only HEAD~1