name: Deploy Database

on:
  push:
    paths:
      - 'db/**'

jobs:
  deploy-db:
    runs-on: ubuntu-latest

    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_SERVICE: geetha_high

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install SQLcl
        run: |
          wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
          unzip sqlcl-latest.zip
          echo "$PWD/sqlcl/bin" >> $GITHUB_PATH
      - name: Verify SQLcl Installation
        run: |
          which sql
          sql -version
      - name: Extract Wallet
        run: |
          echo "${{ secrets.DB_WALLET }}" | base64 -d > wallet.zip
          unzip wallet.zip -d wallet
      - name: Configure Wallet
        run: |
          echo "TNS_ADMIN=$PWD/wallet" >> $GITHUB_ENV
      
      - name: Check Wallet Files
        run: |
          ls -la wallet

      - name: Test Connection
        run: |
          sql ${DB_USER}/${DB_PASSWORD}@{DB_SERVICE}

      - name: Run schema.sql
        run: |
          sql ${DB_USER}/${DB_PASSWORD}@${DB_SERVICE} @db/schema.sql

      - name: Run seed.sql
        run: |
          sql ${DB_USER}/${DB_PASSWORD}@${DB_SERVICE} @db/seed.sql

      - name: Run verify.sql
        run: |
          sql ${DB_USER}/${DB_PASSWORD}@${DB_SERVICE} @db/verify.sql